Azure Endpoint Support
datma-health/TileDB pull request #156
Opened 2023-07-25 22:49 UTC by eneskuluk

Adds endpoint support to Azure. It can be used like following `az://<container><accountname>.<endpoint>/<path>`
`azb://<container>/<path>?<query<endpoint>>`

2023-07-26 06:00 UTC, nalinigans requested changes

2023-07-26 07:31 UTC, eneskuluk commented on core/src/misc/uri.cc
> +      char* az_storage_account_env = getenv("AZURE_STORAGE_ACCOUNT");
Okay, sounds good

2023-07-26 07:31 UTC, eneskuluk commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
Okay, that would be more explicit, will fix that.

2023-07-26 07:37 UTC, eneskuluk commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
Should I keep one of the tests in blob format since that also works, so we would be testing that as well?

2023-07-26 19:11 UTC, nalinigans commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
Can you check if run_dfs_tests is running adls or plain blob, you can pass an additional argument if you like and call `dfs.core.windows.net` or `blob.core.windows.net` appropriately?

2023-07-26 20:20 UTC, eneskuluk commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
Yes, it works. It only uses dfs.core.windows.net in delete_dir function where we call adls client. In other cases, it uses .blob.core.windows.net. That's why we are doing this change [here](https://github.com/OmicsDataAutomation/azure-storage-cpplite/blob/develop/src/storage_account.cpp#L54). When we were not specifying the endpoint, it was going into [this ](https://github.com/OmicsDataAutomation/azure-storage-cpplite/blob/develop/src/storage_account.cpp#L22)if statement where .dfs and .blob is placed correctly and when adls were calling delete_directory, it was using .dfs.core.windows.net and .blob for other cases. With endpoint change, when we set .blob in endpoint through query, it was setting .blob to every variable [here](https://github.com/OmicsDataAutomation/azure-storage-cpplite/blob/master/src/storage_account.cpp#L48), including adls one, so when we were using adls client it was trying to use .blob instead of .dfs. With the changes, we are making sure adls has .dfs and .blob has .dfs so it will use correct urls.
So, both .blob endpoint and .dfs endpoint in query should work since we are making sure it is being set correctly in storage_account.cpp.

2023-07-26 23:39 UTC, nalinigans commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
Agreed. The tests should test the `.blob.` and `.dfs.` endpoints appropriately as that is what will end up in the docs.

2023-07-27 19:47 UTC, eneskuluk commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
I currently did that to first 2 tests, should I do that for every test in run_azure_test or first two is good enough for testing?

2023-07-27 20:05 UTC, nalinigans commented on .github/scripts/run_dfs_tests.sh
> +  echo "az schema utils test" && tiledb_utils_tests "az://$AZURE_CONTAINER_NAME@$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$TEST" && tiledb_utils_tests "azb://$AZURE_CONTAINER_NAME/$TEST?account=$A
That looks good and is sufficient. Thanks @eneskuluk.

2023-07-27 21:19 UTC, mlathara commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
Should this be `AZURE_STORAGE_ENDPOINT` since it could be blob or dfs? I think this is an env var we're introducing (as opposed to leveraging one that AZ CLI or something else also uses) so should be okay to change...?

2023-07-27 22:06 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
Actually, I think there is an official endpoint env. Let me check...

2023-07-27 22:20 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
Not mentioned [here](https://learn.microsoft.com/en-us/azure/storage/blobs/authorize-data-operations-cli.). But, the java.nio implementation for azure storage does mention `AZURE_STORAGE_ENDPOINT` - see [reference](https://github.com/Azure/azure-sdk-for-java/blob/5687bd135f64633a4aa1882fd95be5e8fdb84694/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/DirectoryExample.java#L16). And, the `AZURE_BLOB_ENDPOINT` was introduced before the data lake support and time to retire it. Thanks @mlathara.

2023-07-27 22:28 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
Ah, found it in the `az cli`. Try `az storage blob delete-batch --help` for example. @eneskuluk, please not it is `AZURE_STORAGE_SERVICE_ENDPOINT`!

2023-07-27 22:31 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
btw we don't support `AZURE_STORAGE_CONNECTION_STRING`, but the sdk can authenticate with a connection string too.

2023-07-27 22:39 UTC, mlathara commented on core/src/storage_manager/storage_azure_blob.cc
> +  }
Do we need to leverage the `get_blob_endpoint` function here for `resource_url` as well or am I misunderstanding?

2023-07-27 22:44 UTC, nalinigans requested changes
Looks good, except for the minor changes requested.

2023-07-27 22:44 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +static std::string get_blob_endpoint(std::string endpoint,
Looks like both arguments are constants. Can you change this to 
`get_blob_endpoint(const std::string& endpoint, const std::string& account)`?

2023-07-27 22:44 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +    } else
braces {} for the else condition please.

2023-07-27 22:50 UTC, eneskuluk commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
Should I change AZURE_BLOB_ENDPOINT references to AZURE_STORAGE_SERVICE_ENDPOINT?

2023-07-27 22:53 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +  }
Yes, I think it can be leveraged instead of parsing the path again.

2023-07-27 23:11 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +    char* az_blob_endpoint_env = getenv("AZURE_BLOB_ENDPOINT");
Yes please use the `AZURE_STORAGE_SERVICE_ENDPOINT` env. At least that is what the `az cli` is using.

2023-07-27 23:26 UTC, eneskuluk commented on core/src/storage_manager/storage_azure_blob.cc
> +  }
Since `get_blob_endpoint` can return an empty string (azure cpp library parses it appropriately), this looked easier(and not different in terms of complexity) to me. I can also use `get_blob_endpoint` to pass the argument like following: `get_access_token(azure_account, get_blob_endpoint(arguments here)) `but we still need to check if it has https or not since users can pass with https or without it. Still, there are multiple ways to handle it, not sure which one is the best.

2023-07-28 00:40 UTC, nalinigans commented on core/src/storage_manager/storage_azure_blob.cc
> +  }
That's fine. Leave the code as-is for now.

2023-07-28 18:09 UTC, mlathara approved these changes
lgtm

2023-07-28 21:16 UTC, nalinigans approved these changes
Looks good. Thanks @eneskuluk

2023-07-28 21:16 UTC, merged